.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "SYSTEMCHECK" "1" "January 2020" "systemcheck" "systemcheck Manual"
.SH "NAME"
\fBsystemcheck\fR \- checks security status
.SH "SYNOPSIS"
\fBsystemcheck\fR \fIoptions\fR
.SH "DESCRIPTION"
\fBsystemcheck\fR is a tool, which checks the state of many aspects of the system, which are important for security\.
.SH "OPTIONS"
.IP "\[ci]" 4
\-v, \-\-verbose
.IP
Verbose output\. Outputs results from tests that succeeded, that would otherwise only complain if there was an issue\.
.IP "\[ci]" 4
\-e, \-\-debug
.IP
Debug output\. Enables xtrace and enables curl output\.
.IP "\[ci]" 4
\-\-leak\-tests
.IP
Run Tor leak tests\.
.IP "\[ci]" 4
\-\-show\-ip
.IP
Show IP during Tor leak tests\.
.IP "\[ci]" 4
\-\-gui
.IP
Deactivates output auto detection\. Enables gui output\.
.IP "\[ci]" 4
\-\-cli
.IP
Deactivates output auto detection\. Enables cli output\.
.IP "" 0
.SH "EXIT CODES"
0 Success
.P
1 Error
.P
2 Warning
.P
143 Signal sigterm received\.
.P
130 Signal sigint received\.
.SH "EXAMPLE"
\fBsystemcheck\fR
.P
\fBsystemcheck \-v\fR
.SH "Configuration File and Folder"
See /etc/systemcheck\.d/30_default\.conf
.SH "WWW"
https://www\.whonix\.org/wiki/systemcheck
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
