#!/bin/bash

## Copyright (C) 2012 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

systemd-notify --pid="$$" --ready

while true; do
   echo "$0: INFO: start."
   systemd-notify --pid="$$" WATCHDOG=1

   /usr/libexec/systemcheck/canary

   systemd-notify --pid="$$" WATCHDOG=1
   echo "$0: INFO: end."

   ## 1 hour
   sleep 3600
done
