#!/bin/bash

## Copyright (C) 2025 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Many earlier Kicksecure and Whonix images unintentionally shipped with DKMS
## public and private keys built into the image by the build process, due to
## the fact that DKMS auto-generates these keys when tirdad is initially
## installed. This script detects when one of these unsafe keys is present on
## the machine, and either deletes those keys, or instructs the user to repair
## them if needed.

# shellcheck source=../../../../helper-scripts/usr/sbin/shim-signed-mok-setup
source /usr/sbin/shim-signed-mok-setup
# shellcheck source=../../../../helper-scripts/usr/libexec/helper-scripts/has.sh
source /usr/libexec/helper-scripts/has.sh
# shellcheck source=../../../../helper-scripts/usr/libexec/helper-scripts/secure_boot_enabled_check.bsh
source /usr/libexec/helper-scripts/secure_boot_enabled_check.bsh

cleanup_image_builtin_mok() {
  if [ -f "/var/lib/systemcheck/do_once/${FUNCNAME[0]}_version_1" ]; then
    return 0
  fi

  dkms_mok_variables_set

  if ! has mokutil >/dev/null; then
    ## Intentionally do not set the do_once file yet, as the user might be
    ## using a build-generated MOK key and uninstalled mokutil before
    ## this ran.
    return 0
  fi
  if ! [ -d /sys/firmware/efi ]; then
    ## UEFI is not in use, wipe the MOK keys. This is only done once, and it
    ## will be done on first login, so this should only affect systems that
    ## had pre-built MOK keys.
    safe-rm --force -- "${dkms_mok_public_file}"
    safe-rm --force -- "${dkms_mok_private_file}"
  else
    ## UEFI is in use, see if the key is enrolled.
    ##
    ## Note that we run through these steps even if Secure Boot is disabled,
    ## since the MOK management tooling works even with Secure Boot disabled,
    ## and if the user has a vulnerable key enrolled and then enables Secure
    ## Boot later, they will be vulnerable.
    if [ -f "${dkms_mok_public_file}" ] \
      && ! mokutil_test_key_output="$(mokutil --test-key "${dkms_mok_public_file}" 2>&1)"; then
      if [ "${mokutil_test_key_output}" = "${dkms_mok_public_file} is already enrolled" ]; then
        ## The keys are already enrolled. Because of MOKManager's intentional
        ## design, we cannot rotate the keys without the user's knowledge, so
        ## exit non-zero so systemcheck will warn the user about the keys.
        return 1
      else
        ## We couldn't detect if the keys were enrolled. Exit zero, but
        ## intentionally do not set the do_once file yet, as we might
        ## successfully detect the key state later.
        return 0
      fi
    fi
    ## The MOK is not enrolled. Wipe it if it exists.
    safe-rm --force -- "${dkms_mok_public_file}"
    safe-rm --force -- "${dkms_mok_private_file}"
  fi

  mkdir --parents '/var/lib/systemcheck/do_once'
  touch "/var/lib/systemcheck/do_once/${FUNCNAME[0]}_version_1"
}

cleanup_image_builtin_mok
