#!/bin/bash

## Copyright (C) 2020 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## https://forums.whonix.org/t/one-time-popup-notification-of-whonix-15-deprecation-once-whonix-16-was-released/11720
## https://forums.whonix.org/t/do-not-show-this-message-again-generic-one-time-popup/8066

true "INFO: This version is not yet deprecated."
exit 0

if test -x /usr/libexec/helper-scripts/origins-parser ; then
   source /usr/libexec/helper-scripts/origins-parser
fi

status_file=~/.config/systemcheck/deprecation-notice/dismissed-version-16

title="DEPRECATION NOTICE"

text="<p>$PROJECT_NAME Support Status of this Major Version: <b>Deprecated!</b>
<br />
<br />$PROJECT_NAME major release version <u><code>$derivative_major_release_version</code></u> deprecation date: 14 November 2021.
<br />
<br />No more security support will be provided.
<br />
<br /><b>A Release Upgrade is strongly recommended!</u></b>
<br />
<br />${PROJECT_HOMEPAGE}/wiki/Stay_Tuned
<br />${PROJECT_HOMEPAGE}/wiki/Release_Upgrade
</p>"

/usr/libexec/msgcollector/one-time-popup "$status_file" "$title" "$text"
