#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

source /usr/libexec/helper-scripts/accountctl.sh

readarray -t user_list < <(/usr/libexec/helper-scripts/get-user-list)
for user in "${user_list[@]}"; do
   if [ -n "$(get_pass "${user}")" ]; then
      echo 'Present'
   else
      echo 'Absent'
   fi
done
