#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_autostart() {
   ## If it was not autostarted the user is free to re-run the checks.
   if [ "$manualrun" = "1" ]; then
      return 0
   fi

   if [ "$NOCHECKLASTRUN" = "1" ]; then
      RECENTLY_RUN="0"
   fi

   if [ "$RECENTLY_RUN" = "0" ]; then
      return 0
   else
      ## The check_whonixcheck_lastrun function told us, that whonixcheck has
      ## recently completed (using the
      ## "/var/lib/whonixcheck/"$SCRIPTNAME"_lastrun" status file),
      ## create the recently_run status file.
      sudo -u user touch "/var/run/whonixcheck/${SCRIPTNAME}_recently_run"

      ## If it was run in daemon mode and there is nothing to tell, say nothing,
      ## only send a debug message, if debugging is enabled.
      if [ "$DAEMON" = "1" ]; then
         local MSG="$SCRIPTNAME started in daemon mode. $SCRIPTNAME checks completed $DIFFERENCE seconds ago. No need to run again."

         ## Debugging.
         #$output_x ${output_opts[@]} --passivepopupqueuex --passivepopupqueuextitle "$TITLE_X" --typex "info" --message "$MSG" --done
         ## --done not necessary, the cleanup function will do that.
         #$output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"

         EXIT_CODE="0"
         cleanup "1"
         return 0
      else
         ## Autostarted...
         ## (Not manualrun, we checked that at the top already.)

         if [ ! "$silent" -ge "1" ]; then
            local MSG="No need to run $SCRIPTNAME, was run less than one day ago. You could still start $SCRIPTNAME manually."
            $output_x ${output_opts[@]} --passivepopupqueuex --passivepopupqueuextitle "$TITLE_X" --typex "info" --message "$MSG" --done

            ## --done not necessary, the cleanup function will do that.
            $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
         fi

         EXIT_CODE="0"
         cleanup "1"
         return 0
      fi
   fi
}
