#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_torbrowser() {
   trap "error_handler" ERR

   if [ -f /usr/lib/tbbversion_parser ]; then
      source /usr/lib/tbbversion_parser
   else
      if [ "$verbose" = "1" ]; then
         local MSG="<p>Tor Browser Update Check: tb-updater packages not installed, skipped.</p>"
         $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      fi
      return 0
   fi

   ## Check if TB_LANG exists and is not empty.
   if [[ "$TB_LANG" && "${TB_LANG}" ]]; then
      MSG="<p>Tor Browser Update Check: Tor Browser language variable is set to $TB_LANG.</p>"
   else
      MSG="<p>Tor Browser Update Check: Tor Browser language set to default en-US.</p>"
      TB_LANG="en-US"
   fi
   if [ "$verbose" = "1" ]; then
      $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
   fi

   CHECK_TORBROWSER_RESULT="0"
   local MSG="Tor Browser Update Check: Checking version..."
   $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"

   local SOCKS_PORT_WHONIXCHECK
   SOCKS_PORT_WHONIXCHECK="9110"

   ## This variable gets used by tbbversion.
   RecommendedTBBVersions="$TEMP_DIR/RecommendedTBBVersions"

   ## Getting latest version number
   $CURL \
      --fail \
      $CURL_VERBOSE \
      --socks5-hostname "socks5h://$GATEWAY_IP:$SOCKS_PORT_WHONIXCHECK/" \
      --tlsv1 \
      --proto =https \
      --max-time 180 \
      $CURL_TPO_PIN_CERT \
      --output "$RecommendedTBBVersions" \
      "https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions" \
      &

   lastpid="$!"
   wait "$lastpid" || { CHECK_TORBROWSER_RESULT="$?" ; true; }

   local curl_status_message
   curl_status_message="$(/usr/lib/curl-scripts/curl_exit_codes "$CHECK_TORBROWSER_RESULT")"

   if [ ! "$CHECK_TORBROWSER_RESULT" = "0" ]; then
      local MSG="<p>Tor Browser Update Check Result: <b>Tor Browser Update check failed.</b> (curl exit code: $curl_status_message)
Could not download: <a href=https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions>https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions</a>. Try:
<blockquote>    Start menu -> Applications -> System -> Tor Browser Updater</blockquote></p>"
      $output ${output_opts[@]} --messagex --typex "error" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
      return 0
   fi

   ## sets: tbb_recommended_versions_list
   ## sets: tbbversions_found
   ## sets: tbb_recommended_versions_error
   tbbversion

   ## Used by tbbversion_installed
   [ -n "$tbb_folder" ] || tbb_folder="/home/$user_name/tor-browser_$TB_LANG"

   ## sets: tbb_locally_installed_version
   tbbversion_installed

   if [ "$tbb_locally_installed_version_detect_success" = "1" ]; then
      true "Successfully detected Tor Browser version."
   else
      local MSG="<p>Tor Browser Update Check Result: $tbb_locally_installed_version</p>"
      $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      return 0
   fi

   local up_to_date
   up_to_date="0"
   local tbb_version
   for tbb_version in $tbb_recommended_versions_list; do
      if [ "$tbb_version" = "$tbb_locally_installed_version" ]; then
         up_to_date="1"
         break
      fi
   done

   ## Append to MSG if Tor Browser is current or not.
   if [ "$up_to_date" = "1" ]; then
      ## It is up to date...
      local MSG="<p>Tor Browser Update Check Result: Up to date.</p>"
      $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
   else
      ## Outdated...
      local MSG="<p>Tor Browser Update Check Result: Installed Tor Browser version: $tbb_locally_installed_version.
Latest recommend Tor Browser version(s): $tbb_recommended_versions_list. Please run:
<blockquote>    Start menu -> Applications -> System -> Tor Browser Updater</blockquote></p>"
      $output ${output_opts[@]} --messagex --typex "warning" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "warning" --message "$MSG"
   fi
}
