#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_operating_system() {
   local update_documentation_link_x="<a href=https://www.whonix.org/wiki/Update>Debian Package Update</a>"
   local update_documentation_link_cli="( Documentation: https://www.whonix.org/wiki/Update )"
   ## Running apt-get update as user (non-root).
   ## Depends on exception set in /etc/sudoers.d/.
   ## Minimal custom script.
   local MSG="Debian Package Update Check: Checking for software updates via apt-get... $update_documentation_link_cli"
   $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
   local apt_get_exit_code
   apt_get_exit_code="0"
   sudo "/usr/lib/apt-get-update" >/dev/null &
   apt_get_update_pid="$!"
   wait "$apt_get_update_pid" || { apt_get_exit_code="$?" ; true; };
   unset apt_get_update_pid

   if [ ! "$apt_get_exit_code" = "0" ]; then
      local MSG="<p>$update_documentation_link_x Check Result: <b>Could not check for software updates!</b> (apt-get code: $apt_get_exit_code)
<br></br>Please manually check:
<br></br>(Open a terminal, $start_menu_instructions_system_first_part Terminal.)
<code><blockquote>sudo apt-get update && sudo apt-get dist-upgrade</blockquote></code></p>"
      $output ${output_opts[@]} --messagex --typex "warning" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "warning" --message "$MSG"
      return 0
   fi

   local check_os_output
   check_os_output="$(apt-get --simulate dist-upgrade 2>&1)"

   local number_upgraded line first_char

   ## Can not simply use
   ## number_upgraded="$(echo "$check_os_output" | grep -Po "^\d+ (?=upgraded)")"
   ## because it would break for non-English languages.

   OIFS="$IFS"
   IFS='
'

   for line in $check_os_output; do
      IFS="$OIFS"
      true "line: $line"
      first_char="${line:0:1}"
      if [[ "$first_char" = "" ]]; then
         continue
      fi
      if [[ "$first_char" != *[!0-9]* ]]; then
         true "'$first_char' is strictly numeric."
         read number_upgraded _ <<< "$line"
         true "number_upgraded: $number_upgraded"
         break
      fi
   done

   IFS="$OIFS"

   ## Example number_upgraded:
   ## 55

   if [ "$number_upgraded" = "0" ]; then
      local MSG="<p>$update_documentation_link_x Check Result: No updates found via apt-get.</p>"
      $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      return 0
   fi

   local MSG="<p>$update_documentation_link_x Check Result: <b>apt-get reports that ${number_upgraded} packages can be updated.</b>
<br></br>Please update Whonix-Gateway and Whonix-Workstation:
<br></br>(Open a terminal, $start_menu_instructions_system_first_part Terminal.)
<code><blockquote>sudo apt-get update && sudo apt-get dist-upgrade</blockquote></code></p>"
   $output ${output_opts[@]} --messagex --typex "warning" --message "$MSG"
   $output ${output_opts[@]} --messagecli --typecli "warning" --message "$MSG"
}
