#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x

check_whonixsetup_done_do() {
   trap "error_handler" ERR

   ## Check if /var/lib/whonix/do_once/whonixsetup.done exists.
   if [ -f "/var/lib/whonix/do_once/whonixsetup.done" ]; then
      ## /var/lib/whonix/do_once/whonixsetup.done exists.
      ## whonixsetup already finished earlier, exit.
      whonixsetup_done="1"
      return 0
   else
      ## /var/lib/whonix/do_once/whonixsetup.done does not exist.
      ## whonixsetup not finished yet, continue.
      whonixsetup_done="0"
      return 0
   fi
}

check_whonixsetup_done() {
   trap "error_handler" ERR

   ## sets: whonixsetup_done
   check_whonixsetup_done_do

   if [ "$whonixsetup_done" = "0" ]; then
      local MSG="<p>Please close this window and finish whonixsetup!

<blockquote>    Start Menu -> Applications -> System -> Connection Wizard (Whonix)</blockquote>

    or in Terminal: sudo whonixsetup</p>"

      if [ "$manualrun" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "warning" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "warning" --titlecli "$TITLE" --message "$MSG"
      fi

      EXIT_CODE="1"
      cleanup "1"
      return 0
   else
      local MSG='<p>Check whonixsetup Result: done, ok.</p>'
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
      fi
   fi
}
