#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_tor_bootstrap() {
   ## sets: check_bootstrap_script
   ## sets: lastpid
   ## sets: TOR_BOOTSTRAP_TIME_START
   ## sets: TOR_BOOTSTRAP_TIME_NOW
   ## sets: TOR_BOOTSTRAP_TIME_PASSED
   ## sets: tor_bootstrap_percent
   ## sets: tor_bootstrap_status
   ## sets: tor_bootstrap_timeout_type
   ## sets: tor_circuit_established
   ## sets: tor_circuit_established_check_exit_code
   ## sets: tor_circuit_established_word
   source /usr/lib/anon-shared-helper-scripts/tor_bootstrap_check.bsh
   check_tor_bootstrap_helper

   true "tor_bootstrap_percent: $tor_bootstrap_percent"
   true "tor_bootstrap_status: $tor_bootstrap_status"
   true "tor_circuit_established: $tor_circuit_established"
   true "tor_circuit_established_check_exit_code: $tor_circuit_established_check_exit_code"
   true "tor_circuit_established_word: $tor_circuit_established_word"

   ## Debugging.
   ## Simulating cases where tor_bootstrap_percent is 100 while
   ## tor_circuit_established is 0.
   #if [ "$TOR_BOOTSTRAP_TIME_PASSED" -gt "10" ]; then
      #true
   #else
      #tor_circuit_established="0"
   #fi

   ## `timeout` returns:
   ## - 124 if sigterm was sufficient
   ## - 137 if needed to use kill.

   ## check_socks_port_open_test gets set by check_tor_socks_port_reachability,
   ## which runs earlier.

   if [ "$tor_bootstrap_percent" = "255" ] || [ "$tor_bootstrap_percent" = "124" ] || [ "$tor_bootstrap_percent" = "137" ]; then
      if [ "$VM" = "Whonix-Gateway" ]; then
         local MSG="<p>Tor Bootstrap Result:
<br></br>Tor's Control Port could not be reached!
<br></br>
<br></br>Please report this Whonix bug!
<br></br>
<br></br>(Technical information:)
<br></br>(Code: $tor_bootstrap_percent)
<br></br>(tor_bootstrap_timeout_type: $tor_bootstrap_timeout_type)
<br></br>(tor_bootstrap_status: $tor_bootstrap_status)
<br></br>(check_socks_port_open_test: $check_socks_port_open_test)
<br></br>(Tor Circuit: $tor_circuit_established_word)</p>"
      elif [ "$VM" = "Whonix-Workstation" ]; then
         if [ "$qubes_detected" = "false" ]; then
            local multiple_whonix_ws_msg="<br></br>- If you’re running multiple Whonix-Workstations simultaneously, confirm that separate IP addresses are configured (see <a href=https://www.whonix.org/wiki/Multiple_Whonix-Workstations>https://www.whonix.org/wiki/Multiple_Whonix-Workstations</a>)."
         fi
         local MSG="<p>Tor Bootstrap Result:
<br></br>Tor's Control Port could not be reached!
<br></br>
<br></br>Troubleshooting:
<br></br>- Confirm that Whonix-Gateway is running.
<br></br>- Run <code>whonixcheck</code> on Whonix-Gateway and confirm success.
$multiple_whonix_ws_msg
<br></br>- Rerun <code>whonixcheck</code> here in this Whonix-Workstation.
<br></br>
<br></br>(Technical information:)
<br></br>(Code: $tor_bootstrap_percent)
<br></br>(tor_bootstrap_timeout_type: $tor_bootstrap_timeout_type)
<br></br>(tor_bootstrap_status: $tor_bootstrap_status)
<br></br>(check_socks_port_open_test: $check_socks_port_open_test)
<br></br>(Tor Circuit: $tor_circuit_established_word)</p>"
      else
         local MSG="$FUNCNAME: This is neither Whonix-Gateway nor Whonix-Workstation. Please report this Whonix bug!"
      fi
      if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
         $output_x ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100"
      fi
      $output_x ${output_opts[@]} --messagex --typex "error" --message "$MSG"
      $output_cli ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return 0
   fi

   if [ "$tor_bootstrap_percent" -gt "100" ] || [ "$tor_bootstrap_percent" -lt "0" ]; then
      local MSG="<p>Tor Bootstrap Result:
<br></br>$check_bootstrap_script ERROR ($tor_bootstrap_percent).
<br></br>(tor_bootstrap_status: $tor_bootstrap_status)
<br></br>(check_socks_port_open_test: $check_socks_port_open_test)
<br></br>(Tor Circuit: $tor_circuit_established_word)
<br></br>Please report this Whonix bug!</p>"
      if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
         $output_x ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100"
      fi
      $output_x ${output_opts[@]} --messagex --typex "error" --message "$MSG"
      $output_cli ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return 0
   fi

   ## For testing.
   #if [ "$TOR_BOOTSTRAP_TIME_PASSED" -lt "10" ]; then
      #tor_bootstrap_percent="$(( 5 + ${#RANDOM} ))"
   #fi

   if [ "$tor_bootstrap_percent" = "100" ] && [ "$tor_circuit_established" = "1" ]; then
      local MSG="<p>Tor Bootstrap Result: Connected to Tor.</p>"
      if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
         $output_x ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100"
      fi
      if [ "$DAEMON" = "1" ]; then
         ## Let's not show a success message every time whonixcheck
         ## successfully finished the Tor bootstrap test.
         return 0
      fi
      if [ "$silent" -ge "2" ]; then
         if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
            true "We did not open a progress bar and silent is $silent. Therefore not showing the the passive message."
            return 0
         fi
      fi

      $output_x ${output_opts[@]} --passivepopupqueuex --passivepopupqueuextitle "$TITLE_X" --typex "info" --message "$MSG" --done
      ## Only attempt to close the progress bar if one was started.
      ## Otherwise this might conflict with the progress bar in 25_autostart.
      $output_cli ${output_opts[@]} --waitmessagecli --typecli "info" --message "$MSG" --done
      return 0
   fi

   [ -n "$whonixcheck_tor_bootstrap_wait_max" ] || whonixcheck_tor_bootstrap_wait_max="120"

   if [ "$TOR_BOOTSTRAP_TIME_PASSED" -gt "1" ]; then
      if [ ! "$started_tor_bootstrap_progress_bar" = "1" ]; then
         if [ "$DAEMON" = "1" ]; then
            ## Daemon mode. Not creating a progress bar.
            true
         else
            ## Not running in daemon mode.
            started_tor_bootstrap_progress_bar="1"
            ## Waited for more than 5 seconds.
            local progressbaridx
            progressbaridx="$(cat "/proc/sys/kernel/random/uuid")"
            local MSG="<p>Tor Bootstrap Test: Checking Tor's Bootstrap Status... (Will take up to $whonixcheck_tor_bootstrap_wait_max seconds.)</p>"
            $output_x ${output_opts[@]} --progressbaridx "$progressbaridx" --progressbarx --parentpid "$$" --progressbartitlex "$TITLE_X" --message "$MSG" --done
         fi
      fi
   fi

   if [ "$TOR_BOOTSTRAP_TIME_PASSED" -lt "$whonixcheck_tor_bootstrap_wait_max" ]; then
      if [ "$tor_bootstrap_percent" -lt "100" ] || [ "$tor_circuit_established" = "0" ]; then
         if [ "$PROGRESS" = "" ]; then
            PROGRESS="5"
         fi
         PROGRESS="$(( $PROGRESS + 1 ))"
         if [ "$PROGRESS" -ge "100" ]; then
            PROGRESS="6"
         fi

         if [ "$TOR_BOOTSTRAP_PERCENT_OLD" = "" ]; then
            TOR_BOOTSTRAP_PERCENT_OLD="$tor_bootstrap_percent"
         fi

         if [ "$TOR_BOOTSTRAP_PERCENT_OLD" = "$tor_bootstrap_percent" ]; then
            ## no progress has been made
            local MSG="<p>Tor Bootstrap Result: Bootstrapping for $TOR_BOOTSTRAP_TIME_PASSED seconds. $tor_bootstrap_percent % done. \
Tor Circuit: $tor_circuit_established_word. Tor reports: $tor_bootstrap_status</p>"
         else
            ## progress has been made
            local MSG="<p>Tor Bootstrap Result: Bootstrapping $TOR_BOOTSTRAP_TIME_PASSED seconds. \
Progress has been made. $tor_bootstrap_percent % done. Tor Circuit: $tor_circuit_established_word. Tor reports: $tor_bootstrap_status</p>"
         fi

         TOR_BOOTSTRAP_PERCENT_OLD="$tor_bootstrap_percent"

         $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG" --done
         ## Only attempt to close the progress bar if one was started.
         ## Otherwise this might conflict with the progress bar in 25_autostart.
         if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
            $output_x ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "$PROGRESS"
         fi

         sleep "2" &
         lastpid="$!"
         wait "$lastpid" || true

         check_tor_bootstrap
         return 0
      fi
   elif [ "$TOR_BOOTSTRAP_TIME_PASSED" -ge "$whonixcheck_tor_bootstrap_wait_max" ]; then
      if [ "$VM" = "Whonix-Gateway" ]; then
         local MSG="<p>Tor Bootstrap Result:
<br></br><b>Whonixcheck gave up waiting after $TOR_BOOTSTRAP_TIME_PASSED seconds.</b>
<br></br>Tor Circuit: $tor_circuit_established_word
<br></br>Bootstrapping $tor_bootstrap_percent % done. Tor reports: $tor_bootstrap_status</p>

<p>Possible issues:
<br></br>- Is the host's internet connection working?
<br></br>- Whonix-Gateway will need a few moments for bootstrapping the Tor network.
<br></br>- Do you live in a censored area?</p>

<p>Recommendations:</p>

<p>1)
<br></br>Shut down Whonix and try to get the Tor Browser Bundle from <a href=https://www.torproject.org>https://www.torproject.org</a>
working on your host. If you cannot get the Tor Browser Bundle to work, you will most certainly not get Whonix to work either.</p>

<p>The Tor Browser Bundle is great for testing if you live in a censored area. If you need bridges for the Tor Browser Bundle,
you will need them for Whonix as well.</p>

<p>2)
<br></br>Try again: $start_menu_instructions_system_first_part Whonix Check
<br></br>or in Terminal: <code>whonixcheck</code>
<br></br>or in Terminal with debugging: <code>whonixcheck --debug --verbose</code></p>

<p>3)
<br></br>Use arm, connection page two, to see if Tor is connected:
<blockquote>$start_menu_instructions_system_first_part Arm</blockquote>
or in Terminal: <code>arm</code></p>"
      elif [ "$VM" = "Whonix-Workstation" ]; then
         local MSG="<p>Tor Bootstrap Result:
<br></br>Whonixcheck gave up waiting after $TOR_BOOTSTRAP_TIME_PASSED seconds.
<br></br>Tor Circuit: $tor_circuit_established_word
<br></br>Bootstrapping $tor_bootstrap_percent % done.
<br></br>Tor reports: $tor_bootstrap_status.</p>

<p>Possible issues:
<br></br>- Is the host's internet connection working?
<br></br>- Whonix-Gateway will need a few moments for bootstrapping the Tor network.
<br></br>- Did you start Whonix-Gateway beforehand?</p>

<p>Recommendations:</p>

<p>1)
<br></br>Try again: $start_menu_instructions_system_first_part Whonix Check
<br></br>           or in Terminal: <code>whonixcheck</code>
<br></br>           or in Terminal with debugging: <code>whonixcheck --debug --verbose</code></p>

<p>2)
<br></br>Run whonixcheck on Whonix-Gateway as well.</p>"
      else
         local MSG="$FUNCNAME: This is neither Whonix-Gateway nor Whonix-Workstation. Please report this Whonix bug!"
      fi

      if [ "$started_tor_bootstrap_progress_bar" = "1" ]; then
         $output_x ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100"
      fi
      $output_x ${output_opts[@]} --messagex --typex "error" --message "$MSG"
      $output_cli ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return 0
   else
      error_handler "<p>(Tor Bootstrap Result:)
<br></br>(Technical information:)
<br></br>(tor_bootstrap_percent: $tor_bootstrap_percent)
<br></br>(tor_circuit_established: $tor_circuit_established)
<br></br>(tor_circuit_established_word: $tor_circuit_established_word)
<br></br>(tor_bootstrap_timeout_type: $tor_bootstrap_timeout_type)
<br></br>(tor_bootstrap_status: $tor_bootstrap_status)
<br></br>(check_socks_port_open_test: $check_socks_port_open_test)
<br></br>(TOR_BOOTSTRAP_TIME_PASSED: $TOR_BOOTSTRAP_TIME_PASSED)
<br></br>(whonixcheck_tor_bootstrap_wait_max: $whonixcheck_tor_bootstrap_wait_max)</p>"
   fi
}
