#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_whonix_apt_repository() {
   trap "error_handler" ERR

   local temp_x_tool="<blockquote>Start menu -> Applications -> System -> Whonix Repository</blockquote>"
   local temp_cli_tool="<blockquote><code>sudo whonix_repository</code></blockquote>"

   local temp_base_msg_enabled="<p>Whonix APT Repository: Enabled.
When the Whonix team releases $whonix_codename_uppercase updates,
they will be AUTOMATICALLY installed (when you run apt-get dist-upgrade)
along with updated packages from the Debian team. Please
read <a href=https://www.whonix.org/wiki/Trust>https://www.whonix.org/wiki/Trust</a> to understand the risk.
If you want to change this, use:</p>"

   local temp_base_msg_disabled="<p>Whonix APT Repository: Disabled.
When the Whonix team releases an update, it will be NOT be installed.
Please read <a href=https://www.whonix.org/wiki/Trust>https://www.whonix.org/wiki/Trust</a> to understand the risk.
You will still be notified when updated Whonix packages are released by
whonixcheck's Whonix News. You are free to manually update from source code.
If you want to change this, use:</p>"

   if [ -f "/etc/apt/sources.list.d/whonix.list" ]; then
      local MSG="$temp_base_msg_enabled
    $temp_x_tool"
   else
      local MSG="$temp_base_msg_disabled
    $temp_x_tool"
   fi

   $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"

   if [ -f "/etc/apt/sources.list.d/whonix.list" ]; then
      local MSG="$temp_base_msg_enabled
    $temp_cli_tool"
   else
      local MSG="$temp_base_msg_disabled
    $temp_cli_tool"
   fi

   $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
}
