#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_control_port_filter_running() {
   ## {{ Small check if Control Port Filter Proxy is functional.

   ## Only testing on Whonix-Gateway, because Control Port Filter Proxy only
   ## runs on Whonix-Gateway.
   local i
   i="0"
   if [ "$VM" = "Whonix-Gateway" ]; then
      while [ ! -f "/var/run/control-port-filter-python/pid" ]; do
         i="$(( $i + 1 ))"
         if [ "$i" -ge "30" ]; then
            break
         fi
         sleep "1" &
         lastpid="$!"
         wait "$lastpid" || true
      done
      if [ ! -f "/var/run/control-port-filter-python/pid" ]; then
         local if_you_know_what_you_are_doing_msg
         if_you_know_what_you_are_doing_msg="$(if_you_know_what_you_are_doing_funct "$FUNCNAME")"
         local MSG="<p>Control Port Filter Proxy Test Result:
<br></br><b>File /var/run/control-port-filter-python/pid does not exist.</b>
<br></br>Did you disable Control Port Filter Proxy?
<br></br>If not, please report this Whonix bug!
<br></br>$if_you_know_what_you_are_doing_msg<\p>"
         $output_x ${output_opts[@]} --messagex --typex "error" --message "$MSG"
         $output_cli ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
         EXIT_CODE="1"
         cleanup "1"
         return 0
      else
         local MSG="<p>Control Port Filter Proxy Test Result: OK</p>"
         if [ "$verbose" -ge "1" ]; then
            $output_x ${output_opts[@]} --messagex --typex "info" --message "$MSG"
            $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
         fi
      fi
   fi

   ## }}
}
