#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_kvmclock() {
   trap "error_handler" ERR

   if [ ! -f "/sys/devices/system/clocksource/clocksource0/current_clocksource" ]; then
      local MSG="<p>KVMClock Result: <code>/sys/devices/system/clocksource/clocksource0/current_clocksource</code> does not exist, ok.</p>"
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      fi
      return 0
   fi

   local current_clocksource
   current_clocksource="$(cat "/sys/devices/system/clocksource/clocksource0/current_clocksource")"

   if [ ! "$current_clocksource" = "kvm-clock" ]; then
      local MSG="<p>KVMClock Result: <code>/sys/devices/system/clocksource/clocksource0/current_clocksource</code> exist, is <code>$current_clocksource</code>, not <code>kvm-clock</code>, ok.</p>"
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      fi
      return 0
   fi

   if [ "$WHONIXCHECK_NO_EXIT_ON_KVMCLOCK_DETECTION" = "1" ]; then
      local MSG="<p>KVMClock Test Result: KVMClock detected, but <code>WHONIXCHECK_NO_EXIT_ON_KVMCLOCK_DETECTION</code> is set, continuing.</p>"
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      fi
   else
      local MSG="<p>KVMClock Test Result:

<br></br><b>KVMClock detected! This is unsupported by Whonix developers! Whonixcheck aborted!</b>

<p>Using KVMClock together with Whonix is recommended against, because KVMClock conflicts with Whonix's TimeSync design [1].</p>

<p>You probably did not follow Whonix's KVM instructions. [2]</p>

<p>This might endanger your anonymity. Do not proceed unless you know what you are doing.</p>

<p>If you wish to ignore this warning and to continue whonixcheck anyway, you can set
<code><blockquote>WHONIXCHECK_NO_EXIT_ON_KVMCLOCK_DETECTION=\"1\"</blockquote></code>
in <code>/etc/whonix.d/30_whonixcheck_default</code>.</p>

<p>Recommended action:
<br></br>- Shut down.
<br></br>- Read Whonix documentation. [3]
<br></br>- Follow Whonix's KVM instructions. [2]
<br></br>- Or use Whonix with VirtualBox.
<br></br>- Or use Whonix with Physical Isolation. [4]</p>

<p>[1] <a href=https://www.whonix.org/wiki/Dev/TimeSync>https://www.whonix.org/wiki/Dev/TimeSync</a>
<br></br>[2] <a href=https://www.whonix.org/wiki/KVM>https://www.whonix.org/wiki/KVM</a>
<br></br>[3] <a href=https://www.whonix.org>https://www.whonix.org</a>
<br></br>[4] <a href=https://www.whonix.org/wiki/Physical_Isolation>https://www.whonix.org/wiki/Physical_Isolation</a>
</p>
</p>"

      $output ${output_opts[@]} --messagex --typex "error" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return 0
   fi
}
