#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x

check_whonixsetup_done_do() {
   ## Check if /var/cache/whonix-setup-wizard/status-files/whonixsetup.done exists.
   if [ -f "/var/cache/whonix-setup-wizard/status-files/whonixsetup.done" ]; then
      ## /var/cache/whonix-setup-wizard/status-files/whonixsetup.done exists.
      ## whonixsetup already finished earlier, exit.
      whonixsetup_done="1"
      return 0
   ## Legacy up to build version 9.x.
   elif [ -f "/var/lib/whonix/do_once/whonixsetup.done" ]; then
      whonixsetup_done="1"
      return 0
   else
      ## /var/cache/whonix-setup-wizard/status-files/whonixsetup.done does not exist.
      ## whonixsetup not finished yet, continue.
      whonixsetup_done="0"
      return 0
   fi
}

check_whonixsetup_done() {
   ## sets: whonixsetup_done
   check_whonixsetup_done_do

   if [ "$whonixsetup_done" = "0" ]; then
      local MSG="<p>Please close this window and finish whonixsetup! <blockquote>Start Menu -> Applications -> System -> Connection Wizard (Whonix)</blockquote></p>
<p>or in Terminal: <blockquote><code>sudo whonixsetup</code></blockquote></p>"

      if [ "$manualrun" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "warning" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "warning" --message "$MSG"
      fi

      EXIT_CODE="1"
      cleanup "1"
      return 0
   else
      local MSG='<p>Check whonixsetup Result: done, ok.</p>'
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      fi
   fi
}
