#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x

check_tor_config_do() {
   trap "error_handler" ERR

   ## Fallback.
   tor_verify_config_exit_code="0"

   ## Only check on Whonix-Gateway.
   if [ ! -e "/usr/share/anon-gw-base-files/gateway" ]; then
      tor_verify_config_file="Not running on Whonix-Gateway"
      tor_verify_config_exit_code="0"
      return 0
   fi

   local file_list="/etc/tor/torrc /usr/share/tor/tor-service-defaults-torrc"
   local file_name
   for file_name in $file_list; do
      tor_verify_config_file="$file_name"
      ## This has a /etc/sudoers.d exception.
      tor_verify_config_output="$(sudo tor --verify-config -f "$file_name" 2>&1)" || { tor_verify_config_exit_code="$?" ; true; };
      if [ ! "$tor_verify_config_exit_code" = "0" ]; then
         break
      fi
   done
   unset file_name

   return 0
}

check_tor_config() {
   trap "error_handler" ERR

   ## returns: tor_verify_config_exit_code, tor_verify_config_output
   check_tor_config_do

   if [ ! "$tor_verify_config_exit_code" = "0" ]; then
      local MSG="<p>Tor Config Check Result:
<br></br><b>Your $tor_verify_config_file file contains at least one error.</b></p>

<p>(Tor exit code: $tor_verify_config_exit_code)</p>

<p>Tor reports:
<br></br>$tor_verify_config_output</p>

<p><b>You have to fix this error, before you can use Tor.</b></p>

<p>Please restart Tor after fixing this error.

<blockquote>    Start Menu -> Applications -> System -> Restart Tor</blockquote>
    <br></br>or in Terminal: <code>sudo service tor restart</code></p>

<p>Restart <code>whonixcheck</code> after fixing this error.

<blockquote>    Start Menu -> Applications -> System -> Whonix Check</blockquote>
    <br></br>or in Terminal: <code>whonixcheck</code></p>"
      $output ${output_opts[@]} --messagex --typex "error" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
      EXIT_CODE="1"
      cleanup "1"
      return 0
   else
      local MSG="<p>Tor Config Check Result: $tor_verify_config_file, ok.</p>"
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      fi
   fi
}
