#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_meta_packages() {
   local package_not_installed
   package_not_installed="none"
   if [ "$vm_lower_case_short" = "gateway" ]; then
      if ! dpkg-query --show "whonix-gateway" &> /dev/null ; then
          package_not_installed="whonix-gateway"
      fi
   elif [ "$vm_lower_case_short" = "workstation" ]; then
      if ! dpkg-query --show "whonix-workstation" &> /dev/null ; then
          package_not_installed="whonix-workstation"
      fi
   else
      package_not_installed="unknown"
   fi

   local if_you_know_what_you_are_doing_msg see_also_link
   if_you_know_what_you_are_doing_msg="$(if_you_know_what_you_are_doing_funct "$FUNCNAME")"
   see_also_link="<a href=https://www.whonix.org/wiki/Whonix_Debian_Packages>https://www.whonix.org/wiki/Whonix_Debian_Packages</a>"

   if [ "$package_not_installed" = "none" ]; then
      local MSG="<p>Whonix Meta Packages Test Result: $package_not_installed missing. (See also: $see_also_link)</p>"
      if [ "$verbose" -ge "1" ]; then
         $output_x ${output_opts[@]} --messagex --typex "info" --message "$MSG"
         $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      fi
      return 0
   elif [ "$package_not_installed" = "unknown" ]; then
      local MSG="<p>Whonix Meta Packages Test Result: Neither Whonix-Gateway nor Whonix-Workstation detected.
Therefore unchecked, if either the <code>whonix-gateway</code> or <code>whonix-workstation</code> meta packages is installed.
<br />See also: $see_also_link
<br />$if_you_know_what_you_are_doing_msg</p>"
   else
      local MSG="<p>Whonix Meta Packages Test Result: $VM detected, but the meta package <code>$package_not_installed</code> is not installed.
Did you accidentally uninstall it?
<br />See also: $see_also_link
<br />$if_you_know_what_you_are_doing_msg</p>"
   fi

   $output_x ${output_opts[@]} --messagex --typex "warning" --message "$MSG"
   $output_cli ${output_opts[@]} --messagecli --typecli "warning" --message "$MSG"
}

check_unwanted_packages() {
   local unwanted_package unwanted_packages_list unwanted_packages_counter dpkg_query_result
   unwanted_packages_counter="0"
   for unwanted_package in $whonixcheck_unwanted_package ; do
      dpkg_query_result="$(dpkg-query --show --showformat='${Status}' "$unwanted_package" 2>/dev/null)" || true
      if [ "install ok installed" = "$dpkg_query_result" ]; then
         unwanted_packages_counter="$(( $unwanted_packages_counter + 1 ))"
         unwanted_packages_list+="$unwanted_package "
      fi
   done

   if [ "$unwanted_packages_counter" = "0" ]; then
      local MSG="<p>Whonix Unwanted Packages Test Result: None found.</p>"
      if [ "$verbose" -ge "1" ]; then
         $output_x ${output_opts[@]} --messagex --typex "info" --message "$MSG"
         $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      fi
      return 0
   fi

   local if_you_know_what_you_are_doing_msg see_also_link
   if_you_know_what_you_are_doing_msg="$(if_you_know_what_you_are_doing_funct "$FUNCNAME")"
   see_also_link="<a href=https://www.whonix.org/wiki/Whonix_Debian_Packages>https://www.whonix.org/wiki/Whonix_Debian_Packages</a>"

   if [ "$qubes_detected" = "true" ]; then
      if [ "$qubes_vm_persistence" = "full" ]; then
         ## Running in either StandaloneVM or TemplateVM.
         local qubes_update_help="<br></br>1. Open a terminal. ($persistent_changes_start_menu_instructions_first_part Terminal)
<br></br>2. Purge. <blockquote><code>sudo apt-get purge $unwanted_packages_list</code></blockquote>"
      else
         ## TemplateBasedVM
         local qubes_update_help="<br></br>1. Open a terminal. ($persistent_changes_start_menu_instructions_first_part Terminal)
<br></br>2. Purge <blockquote><code>sudo apt-get purge $unwanted_packages_list</code></blockquote>
3. Shutdown your TemplateVM. (dom0 -> Qubes VM Manager -> right click '<code>$qubes_base_template</code>' -> Shutdown VM)
<br></br>4. Shutdown and restart this Template-Based <code>$qubes_vm_type</code>. (dom0 -> Qubes VM Manager -> right click '<code>$qubes_name_of_vm</code>' -> Shutdown VM)"
      fi
   fi

   local MSG="<p>Whonix Unwanted Packages Test Result: $unwanted_packages_counter unwanted package(s) installed. \
It is recommended that you remove them from $update_where.
$qubes_update_help
<br />See also: $see_also_link
<br />$if_you_know_what_you_are_doing_msg</p>"
   $output_x ${output_opts[@]} --messagex --typex "warning" --message "$MSG"
   $output_cli ${output_opts[@]} --messagecli --typecli "warning" --message "$MSG"
}

check_packages() {
   check_meta_packages
   check_unwanted_packages
}
