#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_tor_enabled() {
   ## provided by: /usr/lib/anon-shared-helper-scripts/tor_enabled_check
   ## sets: TOR_ENABLED
   check_tor_enabled_do

   if [ "$TOR_ENABLED" = "0" ]; then
      ## When Tor is not yet enabled, i.e. if "DisableNetwork 1" is in
      ## commented /etc/tor/torrc and/or
      ## /usr/share/tor/tor-service-defaults-torrc and whonixcheck is
      ## manually started, show the following message and exit.
      ## Otherwise, if whonixcheck is automatically started just be quit and
      ## exit.

      local MSG="<p>Tor Check Result:
<b>Tor is disabled.</b> Therefore you most likely can not connect to the internet.<br /><br />
(Debugging information: Could not find <code>DisableNetwork 0</code> in <code>/etc/tor/torrc</code>.)<br /><br />
Please close this window and enable Tor using Whonix Setup!
<blockquote>    $start_menu_instructions_system_first_part Whonix Setup</blockquote>
    or in Terminal: <code>sudo whonixsetup</code><br /><br />
or manually (if you know about the public Tor network and : Open <code>/etc/tor/torrc</code> with root rights and set:
<blockquote><code>DisableNetwork 0</code></blockquote>
Then run <code>whonixcheck</code> again.</p>"

      if [ "$manualrun" = "1" ]; then
         $output ${output_opts[@]} --messagecli --typecli "warning" --message "$MSG"
         $output ${output_opts[@]} --messagex --typex "warning" --message "$MSG"
      fi

      EXIT_CODE="1"
      cleanup "1"
      return 0
   else
      if [ -e "/usr/share/anon-gw-base-files/gateway" ]; then
         local MSG='<p>Tor Check Result: "DisableNetwork 1" in /etc/tor/torrc commented out, ok.</p>'
         if [ "$verbose" -ge "1" ]; then
            $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
         fi
      else
         local MSG='<p>Tor Check Result: Not running on Whonix-Gateway, ok.</p>'
         if [ "$verbose" -ge "1" ]; then
            $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
         fi
      fi
   fi
}
