#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_qubes_update_proxy() {
   if [ ! "$verbose" -ge "1" ]; then
      return 0
   fi

   local MSG="<p>Qubes Update Proxy Test: Trying to reach Qubes update proxy...</p>"
   $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"

   local ip
   if [ "$vm_lower_case_short" = "gateway" ]; then
      ip="127.0.0.1"
   else
      ip="10.137.255.254"
   fi

   local qubes_update_proxy_test_curl_exit_code
   qubes_update_proxy_test_curl_exit_code="0"

   http_proxy="http://$ip:8082" \
      $CURL \
         --fail \
         $CURL_VERBOSE \
         --max-time 10 \
         --output "$TEMP_DIR/qubes_update_proxy_file" \
         http://deb.qubes-os.org/r3.0/vm/dists/jessie/Release \
         &

   ## Example OK:
   ## Origin: Qubes Debian
   ## Label: Qubes Debian
   ## [...]

   ## Example Failure:
   ## curl: (22) The requested URL returned error: 403 Filtered

   ## Example Failure:
   ## curl: (7) Failed to connect to 127.0.0.1 port 8082: Connection refused

   lastpid="$!"
   wait "$lastpid" || { qubes_update_proxy_test_curl_exit_code="$?" ; true; };

   local curl_status_message
   curl_status_message="$(/usr/lib/curl-scripts/curl_exit_codes "$qubes_update_proxy_test_curl_exit_code")"

   if [ "$qubes_update_proxy_test_curl_exit_code" = "22" ]; then
      local MSG="<p>Qubes Update Proxy Result: Failed. (Filtered.) \
(curl exit code: $qubes_update_proxy_test_curl_exit_code | curl status message: $curl_status_message)</p>"
      $output_x ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      return 0
   fi

   if [ "$qubes_update_proxy_test_curl_exit_code" = "7" ]; then
      local MSG="<p>Qubes Update Proxy Result: Failed. (Update proxy not reachable.) \
(curl exit code: $qubes_update_proxy_test_curl_exit_code | curl status message: $curl_status_message)</p>"
      $output_x ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      return 0
   fi

   if [ ! "$qubes_update_proxy_test_curl_exit_code" = "0" ]; then
      local MSG="<p>Qubes Update Proxy Result: Unknown issue. \
(curl exit code: $qubes_update_proxy_test_curl_exit_code | curl status message: $curl_status_message)</p>"
      $output_x ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      return 0
   fi

   local MSG="<p>Qubes Update Proxy Result: Ok, reachable.</p>"
   $output_x ${output_opts[@]} --messagex --typex "info" --message "$MSG"
   $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
}
