#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_tor_enabled() {
   ## provided by: /usr/lib/anon-shared-helper-scripts/tor_enabled_check
   ## sets: TOR_ENABLED
   check_tor_enabled_do

   if [ "$TOR_ENABLED" = "0" ]; then
      ## When Tor is not yet enabled, i.e. if "DisableNetwork 1" is in
      ## commented /etc/tor/torrc and/or
      ## /usr/share/tor/tor-service-defaults-torrc and whonixcheck is
      ## manually started, show the following message and exit.
      ## Otherwise, if whonixcheck is automatically started just be quit and
      ## exit.

      local MSG="Tor Check Result:
No network. Tor is disabled.
Please enable Tor!
Start Menu -> Applications -> System -> Connection Wizard (Whonix)
or in Terminal: sudo whonixsetup"

      if [ "$manualrun" = "1" ]; then
         $output ${output_opts[@]} --messagecli --typecli "warning" --message "$MSG"
      fi

      local MSG="<p>Tor Check Result:
<b>No network. Tor is disabled.</b></p>

<p>Please close this window and enable Tor!

<blockquote>    Start Menu -> Applications -> System -> Connection Wizard (Whonix)</blockquote>

    or in Terminal: <code>sudo whonixsetup</code></p>"

      if [ "$manualrun" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "warning" --message "$MSG"
      fi

      EXIT_CODE="1"
      cleanup "1"
      return 0
   else
      if [ -e "/usr/share/anon-gw-base-files/gateway" ]; then
         local MSG='<p>Tor Check Result: "DisableNetwork 1" in /etc/tor/torrc commented out, ok.</p>'
         if [ "$verbose" = "1" ]; then
            $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
         fi
      else
         local MSG='<p>Tor Check Result: Not running on Whonix-Gateway, ok.</p>'
         if [ "$verbose" = "1" ]; then
            $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
         fi
      fi
   fi
}
