#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

download_whonix_news() {
   whonixcheck_run_function whonix_news_preparation

   whonixcheck_run_function download_now_whonix_news

   if [ ! "$whonix_news_download_success" = "true" ]; then
      true "$BASH_SOURCE WARNING: whonix_news_download_success is not true, it is $whonix_news_verified_ok, return"
      return 0
   fi

   whonixcheck_run_function verify_whonix_news

   if [ ! "$whonix_news_verified_ok" = "true" ]; then
      true "$BASH_SOURCE WARNING: whonix_news_verified_ok is not true, it is $whonix_news_verified_ok, return"
      return 0
   fi

   whonixcheck_run_function extract_whonix_news

   if [ ! "$whonix_news_tar_exit_code" = "0" ]; then
      true "$BASH_SOURCE ERROR: whonix_news_tar_exit_code is not 0, it is $whonix_news_tar_exit_code, return"
      return 0
   fi

   whonixcheck_run_function check_whonix_debian_version
   whonixcheck_run_function check_whonix_build_version

   whonixcheck_run_function check_whonix_debian_news
   whonixcheck_run_function check_whonix_build_news

   whonixcheck_run_function check_whonix_show_news
}

whonix_news_preparation() {
   if [ "$TEMP_DIR" = "" ]; then
      error "Variable TEMP_DIR is empty!"
      return 0
   fi

   whonix_news_hyperlink="<a href=https://www.whonix.org/wiki/Whonix_News>Whonix News</a>"

   whonix_news_download_dir="$TEMP_DIR/news/news_download_dir"
   whonix_news_verify_dir="$TEMP_DIR/news_verify_dir"

   SOCKS_PORT_WHONIX_NEWS="9114"

   local MSG="Whonix News Download: Checking for Whonix news and updates..."
   $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"

   mkdir --parents "$whonix_news_download_dir"
   mkdir --parents "$whonix_news_verify_dir"

   declare -A -g whonix_news_web_link_list
   declare -A -g whonix_news_download_exit_code

   ## whonix_news_web_link_list["web_link"]="file_name"
   whonix_news_web_link_list["http://sourceforge.net/projects/whonixdevelopermetafiles/files/internal/news_v4/whonix_news.tar.xz.asc/download"]="whonix_news.tar.xz.asc"
   whonix_news_web_link_list["http://sourceforge.net/projects/whonixdevelopermetafiles/files/internal/news_v4/whonix_news.tar.xz/download"]="whonix_news.tar.xz"
}

download_now_whonix_news() {
   ## sf.net does not support ssl.
   ## --location is required since sf.net uses redirects to mirrors.

   local web_link

   for web_link in "${!whonix_news_web_link_list[@]}"; do
      ## Fallback.
      whonix_news_download_success="false"

      local file_name
      file_name="${whonix_news_web_link_list[$web_link]}"

      true "web_link: $web_link"
      true "file_name: $file_name"

      whonix_news_download_exit_code["$web_link"]="0"

      $CURL \
         $CURL_VERBOSE \
         --fail \
         --proxy "socks5h://user:password@$GATEWAY_IP:$SOCKS_PORT_WHONIX_NEWS" \
         --location \
         --max-time 180 \
         --output "$whonix_news_download_dir/$file_name" \
         "$web_link" \
         &

      lastpid="$!"
      wait "$lastpid" || { whonix_news_download_exit_code["$web_link"]="$?" ; true; };

      if [ ! "${whonix_news_download_exit_code[$web_link]}" = "0" ]; then
         whonix_news_download_success="false"
         local curl_status_message
         curl_status_message="$(/usr/lib/curl-scripts/curl_exit_codes "${whonix_news_download_exit_code[$web_link]}")"
         local MSG="<p>$whonix_news_hyperlink Result: Download Whonix News File failed. \
(file_name: <code>$file_name</code> | web_link: <code>$web_link</code> | curl exit code: <code>$curl_status_message</code>)</p>"
         $output ${output_opts[@]} --messagex --typex "error" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
         return 0
      fi

      whonix_news_download_success="true"
      if [ "$verbose" = "1" ]; then
         local curl_status_message
         curl_status_message="$(/usr/lib/curl-scripts/curl_exit_codes "${whonix_news_download_exit_code[$web_link]}")"
         local MSG="<p>$whonix_news_hyperlink Result: Download Whonix News File succeeded. \
(file_name: <code>$file_name</code> | web_link: <code>$web_link</code> | curl exit code: <code>$curl_status_message</code>)</p>"
         $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
      fi

   done
}

verify_whonix_news() {
   ## Fallback
   whonix_news_verified_ok="false"

   gpg_bash_lib_input_key_import_dir="/usr/share/whonix/whonix-news-keys.d"
   gpg_bash_lib_input_temp_folder="$whonix_news_verify_dir/news_gpg"
   gpg_bash_lib_input_data_file="$whonix_news_download_dir/whonix_news.tar.xz"
   gpg_bash_lib_input_sig_file="$whonix_news_download_dir/whonix_news.tar.xz.asc"
   gpg_bash_lib_input_file_name_enforce="true"
   gpg_bash_lib_input_cleanup="false"
   gpg_bash_lib_input_error_handler_extra='error_handler "$gpg_bash_lib_output_error_handler_message"'

   source "/usr/lib/gpg-bash-lib/source_all"

   trap "gpg_bash_lib_function_error_handler" ERR
   gpg_bash_lib_function_main_verify
   trap "error_handler" ERR

   gpg_bash_lib_output_diagnostic_message="$(/usr/lib/msgcollector/br_add "$gpg_bash_lib_output_diagnostic_message")"

   local MSG="<p>$whonix_news_hyperlink Check: gpg_bash_lib_output_diagnostic_message:<br></br>
$gpg_bash_lib_output_diagnostic_message</p>"
   if [ "$verbose" = "1" ]; then
      $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
   fi

   if [ ! "$gpg_bash_lib_output_alright_status" = "true" ] || [ "$gpg_bash_lib_output_failure" = "true" ] ; then
      whonix_news_verified_ok="false"
      local MSG="<p>$whonix_news_hyperlink Download Result:<br></br><b>Could not OpenPGP verify authenticity of Whonix News </b>$file_name!!!
<br></br>(gpg_bash_lib_output_gpg_verify_exit_code: $gpg_bash_lib_output_gpg_verify_exit_code \
| gpg_bash_lib_output_validsig_status: $gpg_bash_lib_output_validsig_status | \
gpg_bash_lib_output_alright_status: $gpg_bash_lib_output_alright_status | \
gpg_bash_lib_output_failure: $gpg_bash_lib_output_failure)
<br></br>This is either,
<br></br>- a Whonix Bug,
<br></br>- an attack on Whonix,
<br></br>- or Whonix News Keys might be outdated. Upgrading using apt-get might fix this.</p>"
      $output ${output_opts[@]} --messagex --typex "error" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
      return 0
   fi

   case "$gpg_bash_lib_output_freshness_detail" in
      "lenient")
         local MSG="<p>$whonix_news_hyperlink Check: <br></br><b>Your clock might be slow.</b> According to your system clock,
Whonix News File was signed $gpg_bash_lib_output_signed_on_unixtime_minus_current_unixtime_pretty before current time.
Ignoring this, because it still is within range. (Whonix News File Signatures are valid up to $gpg_bash_lib_output_maximum_age_pretty_output before.)</p>"
         if [ "$verbose" = "1" ]; then
            $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
         fi
         ;;
      "slow")
         whonix_news_verified_ok="false"
         local MSG="<p>$whonix_news_hyperlink Check: <br></br><b>Your clock might be slow.</b> According to your system clock,
Whonix News File was signed $gpg_bash_lib_output_signed_on_unixtime_minus_current_unixtime_pretty before current time.
<br></br>Please run Timesync: <blockquote>Start menu -> Applications -> System -> Timesync</blockquote>
or in Terminal: <code><blockquote>timesync</blockquote></code></p>"
         $output ${output_opts[@]} --messagex --typex "error" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
         return 0
         ;;
      "outdated")
         whonix_news_verified_ok="false"
         local MSG="<p>$whonix_news_hyperlink Check: <b>Whonix News File is no longer valid (outdated).</b>
<br></br>Either,
<br></br>- your clock might be fast (at least $gpg_bash_lib_output_in_future_pretty_output fast). In that case, please run Timesync: <blockquote>Start menu -> Applications -> System -> Timesync</blockquote>
                     or in Terminal: <code><blockquote>timesync</blockquote></code>
- it has been forgotten to refresh Whonix's News File by Whonix maintainers (invalid since $gpg_bash_lib_output_in_future_pretty_output)
<br></br>- this is a Whonix Bug
<br></br>- or this is an attack on Whonix</p>"
         $output ${output_opts[@]} --messagex --typex "error" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
         return 0
         ;;
      "current")
         local MSG="<p>$whonix_news_hyperlink Check: According to your system clock, Whonix News File was signed $gpg_bash_lib_output_current_unixtime_minus_signed_on_unixtime_pretty ago. \
(Whonix News File Signatures are valid up to $gpg_bash_lib_output_maximum_age_pretty_output.)</p>"
         if [ "$verbose" = "1" ]; then
            $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
         fi
         ;;
      *)
         whonix_news_verified_ok="false"
         error "gpg_bash_lib_output_freshness_detail is neither lenient, nor slow, nor outdated, nor current, it is: $gpg_bash_lib_output_freshness_detail"
         return 0
         ;;
   esac

   whonix_news_verified_ok="true"

   local MSG="<p>$whonix_news_hyperlink Check: gpg_bash_lib_output_freshness_msg:<br></br>
$gpg_bash_lib_output_freshness_msg</p>"
   if [ "$verbose" = "1" ]; then
      $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
   fi

   local MSG="<p>$whonix_news_hyperlink Check: news file valid.</p>"
   if [ "$verbose" = "1" ]; then
      $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
   fi
}

extract_whonix_news() {
   local file_name timeout_after kill_after
   file_name="whonix_news.tar.xz"

   timeout_after="10"
   kill_after="10"

   ## Debugging.
   #timeout_after="0.001"
   #kill_after="0.001"

   whonix_news_tar_exit_code="0"

   timeout --kill-after="$kill_after" "$timeout_after" \
      tar \
         --extract \
         --verbose \
         --xz \
         --file="$whonix_news_download_dir/$file_name" \
         --directory="$whonix_news_download_dir/" \
         . \
         >/dev/null \
         &

   lastpid="$!"
   wait "$lastpid" || { whonix_news_tar_exit_code="$?" ; true; };

   ## `timeout` returns:
   ## - 124 if sigterm was sufficient
   ## - 137 if needed to use kill.

   if [ ! "$whonix_news_tar_exit_code" = "0" ]; then
      local MSG="<p>$whonix_news_hyperlink Download Result: <b>Could not extract $file_name!</b> (tar exit code: ${whonix_news_tar_exit_code})
<br></br>Please report this bug!</p>"
      $output ${output_opts[@]} --messagex --typex "error" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
      return 0
   fi

   ## Debugging.
   #ls -la "$whonix_news_download_dir/"
}

check_whonix_debian_version() {
   local file_name
   file_name="$whonix_news_download_dir/whonix_${vm_lower_case_short}_valid_deb_versions"

   if [ ! -f "$file_name" ]; then
      ## This file should always exist.
      whonix_news_result_output="<b>File $file_name does not exist.</b><br></br>Please report this bug!"
      return 0
   fi

   whonix_news_deb_up_to_date="false"

   local LINE
   while read -r LINE; do
      #true "$i: $LINE"
      if [ "$whonix_deb_package_version" = "$LINE" ]; then
         whonix_news_deb_up_to_date="true"
      fi
   done < "$file_name"

   if [ "$whonix_news_deb_up_to_date" = "true" ]; then
      ## Up to date...
      whonix_news_result_output="<span style=color:#008000>√</span> Up to date: <code>$whonix_deb_package_name</code> <u>$whonix_deb_package_version</u>"
   else
      ## Outdated...
      whonix_news_result_output="<b><span style=font-weight:600;color:#ff0000>✘</span> Outdated: Installed <code>$whonix_deb_package_name</code> <u>$whonix_deb_package_version</u> is outdated!</b>
<br></br>You should update. You can automatically update using Whonix's internal updater. Please update using:
<code><blockquote>sudo apt-get update && sudo apt-get dist-upgrade</blockquote></code>"
   fi
}

check_whonix_build_version() {
   local file_name
   file_name="$whonix_news_download_dir/whonix_${vm_lower_case_short}_valid_build_versions"

   if [ ! -f "$file_name" ]; then
      ## This file should always exist.
      whonix_news_result_output="${whonix_news_result_output}<br></br>
<b>File $file_name does not exist.</b><br></br>Please report this bug!"
      return 0
   fi

   whonix_news_build_up_to_date="false"

   local LINE
   while read -r LINE; do
      #true "$i: $LINE"
      if [ "$whonix_build_version" = "$LINE" ]; then
         whonix_news_build_up_to_date="true"
      fi
   done < "$file_name"

   if [ "$whonix_news_build_up_to_date" = "true" ]; then
      ## Up to date...
      whonix_news_result_output="${whonix_news_result_output}<br></br>
<span style=color:#008000>√</span> Up to date: Whonix Build Version <u>$whonix_build_version</u>"
   else
      ## Outdated...
      whonix_news_result_output="${whonix_news_result_output}<br></br>
<span style=font-weight:600;color:#ff0000>✘</span> <b>Outdated: Whonix Build Version <u>$whonix_build_version</u> is outdated!</b>
<br></br>You should update. Sorry, automatically updating this Whonix version is not possible. You have to manually download a new Whonix image."
   fi
}

check_whonix_debian_news() {
   local file_name
   file_name="$whonix_news_download_dir/whonix_${vm_lower_case_short}_${whonix_deb_package_version}_deb_news"

   if [ ! -f "$file_name" ]; then
      ## This will happen:
      ## - when using custom git tags / versions
      ## - when no news file has been uploaded yet
      if [ "$verbose" = "1" ]; then
         whonix_news_result_output="${whonix_news_result_output}<br></br>
There is no news file available for <code>$whonix_deb_package_name</code> version <u>${whonix_deb_package_version}</u> yet."
      fi
   else
      local message
      message="$(cat "$file_name")"
      message="$(/usr/lib/msgcollector/striphtml "$message")"
      if [ "$message" = "" ]; then
         return 0
      fi
      whonix_news_result_output="${whonix_news_result_output}<br></br>
$VM <code>$whonix_deb_package_name</code> <u>${whonix_deb_package_version}</u> News: <code><blockquote>$message</blockquote></code>"
   fi
}

check_whonix_build_news() {
   local file_name
   file_name="$whonix_news_download_dir/whonix_${vm_lower_case_short}_${whonix_build_version}_build_news"

   if [ ! -f "$file_name" ]; then
      ## This will happen:
      ## - when using custom git tags / versions
      ## - when no news file has been uploaded yet
      if [ "$verbose" = "1" ]; then
         whonix_news_result_output="${whonix_news_result_output}<br></br>
There is no news file available for Whonix Build Version <u>${whonix_build_version}</u> yet."
      fi
   else
      local message
      message="$(cat "$file_name")"
      message="$(/usr/lib/msgcollector/striphtml "$message")"
      if [ "$message" = "" ]; then
         return 0
      fi
      whonix_news_result_output="${whonix_news_result_output}<br></br>
$VM Build <u>${whonix_build_version}</u> News: <code><blockquote>$message</blockquote></code>"
   fi
}

check_whonix_show_news() {
   local type
   type="info"
   if [ ! "$whonix_news_build_up_to_date" = "true" ]; then
      type="warning"
   fi
   if [ ! "$whonix_news_deb_up_to_date" = "true" ]; then
      type="warning"
   fi

   local MSG="<p>$whonix_news_hyperlink Result:<br></br>
$whonix_news_result_output</p>"
   $output ${output_opts[@]} --messagex --typex "$type" --message "$MSG"
   $output ${output_opts[@]} --messagecli --typecli "$type" --message "$MSG"
}
