#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## {{ maybe_kill_apt_get_update
##
## apt-get-update runs as root (using a /etc/sudoers.d/ exception) while
## whonixcheck runs as user. Therefore we can't kill apt-get-update using
## process_killer_helper. (Can't kill processes owned by other users.)
## In case apt-get-update is still running, we need to start
## apt-get-update-kill-helper as root (again using a /etc/sudoers.d/
## exception). This might look like a lot effort for little gain, but when
## the user terminated whonixcheck, apt-get is still running and the user wants
## to manually use apt-get, it would show an error because the apt-get lockfile
## would still exist.
maybe_kill_apt_get_update() {
   if [ "$apt_get_update_pid" = "" ]; then
      ## Pid never set. Either the check_operating_system check has been disabled,
      ## or signal received earlier or this isn't whonixcheck. Either way.
      ## Nothing to do.
      return 0
   fi

   ## Can not use `kill`, must use `ps`, because kill will always return a
   ## a non-zero exit code if the process is owned by a different user.
   local ps_p_exit_code
   ps_p_exit_code="0"
   ps -p "$apt_get_update_pid" >/dev/null 2>/dev/null || { ps_p_exit_code="$?" ; true; };

   if [ ! "$ps_p_exit_code" = "0" ]; then
      ## apt-get-update already terminated, nothing to do.
      return 0
   fi
   ## apt-get-update still running.

   if [ ! -x "/usr/lib/anon-shared-helper-scripts/apt-get-update-kill-helper" ]; then
      error "/usr/lib/anon-shared-helper-scripts/apt-get-update-kill-helper is not executable."
   fi

   ## There is an exception in /etc/sudoers.d/.
   ## "|| true", to avoid an error when whonixcheck receives a sigterm signal
   ## while running this command (such as when whonixcheckd gets stopped).
   sudo "/usr/lib/anon-shared-helper-scripts/apt-get-update-kill-helper" "$apt_get_update_pid" || true
}
## }}

cleanup_files() {
   trap "error_handler" ERR

   if [ "$DEL_TMP" = "false" ]; then
      echo "$SCRIPTNAME: Not deleting TEMP_DIR: $TEMP_DIR"
   else
      if [ -d "$TEMP_DIR" ]; then
         rm --recursive "$TEMP_DIR"
      fi

      rm --force "/var/run/whonixcheck/${IDENTIFIER}_running"
      rm --force "/var/run/whonixcheck/${IDENTIFIER}_waiting"
      #rm --force "/var/run/whonixcheck/${IDENTIFIER}_pid"
   fi
}

## {{ ex_funct

## This function gets called by trap_sigterm (ex: zenity cancel button),
## trap_sigint (ex: ctrl + c) and error_handler.

ex_funct() {
   trap "error_handler" ERR

   if [ ! "$SIGNAL_TYPE" = "NONE" ]; then
      echo "$SCRIPTNAME: signal $SIGNAL_TYPE received. Cleaning up... Exiting..."
   fi

   ## Deactivate traps, so when pressing ctrl + c several times this won't
   ## create an endless loop.
   trap - SIGTERM
   trap - SIGINT
   trap - SIGUSR2

   maybe_kill_apt_get_update

   ## kill $lastpid (if running)
   process_killer_helper

   lastpid="$tail_pid"
   ## kill $lastpid (if running)
   process_killer_helper

   cleanup_files

   ## Check if $output command has been already defined. This is not the case,
   ## when the script is terminated very early.
   local command_v_output_exit_code
   command_v_output_exit_code="0"
   command -v "$output" >/dev/null || { command_v_output_exit_code="$?" ; true; };
   if [ "$command_v_output_exit_code" = "0" ]; then
      local output_status_exit_code
      output_status_exit_code="0"
      $output ${output_opts[@]} --identifier "$IDENTIFIER" --status --messagecli || { output_status_exit_code="$?" ; true; };

      ## The "Please feel free to press <enter> to return back to your normal prompt."
      ## message is not necessary when manually started.
      if [ ! "$manualrun" = "1" ]; then
         ## Not manually started.
         if [ "$output_status_exit_code" = "0" ]; then
            ## We have messages to show.
            ## Add press enter to return back to your normal prompt message below.
            local MSG="<p>Please feel free to press enter to return back to your normal prompt.</p>"
            $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
         elif [ "$output_status_exit_code" = "1" ]; then
            true "No messages for --messagecli in the queue. Not adding press enter to return back to your normal prompt message below."
         else
            local MSG="<p><b>$output returned $output_status_exit_code.</b> Please report this bug!</p>"
            $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
            $output ${output_opts[@]} --messagex --typex "error" --message "$MSG"
         fi
      fi

      if [ ! "$progressbaridx" = "" ]; then
         local progress_bar_open
         progress_bar_open="0"
         $output ${output_opts[@]} --identifier "$IDENTIFIER" --status --progressbaridx "$progressbaridx" --progressbarxrunning || { progress_bar_open="$?" ; true; };
      fi

      if [ "$SIGNAL_TYPE" = "SIGUSR2" ]; then
         true "User most likely pressed cancel button. No need to send progress 100 to close progress bar."
      else
         if [ "$progress_bar_open" = "0" ]; then
            $output ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100"
         else
            true "No progress bar open. No need to send progress 100 to close progress bar."
         fi
      fi

      if [ ! "$SIGNAL_TYPE" = "NONE" ]; then
         local MSG="<p><b>$SCRIPTNAME aborted!</b> (SIGNAL_TYPE: $SIGNAL_TYPE)</p>"
         $output ${output_opts[@]} --messagex --typex "warning" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "warning" --message "$MSG"
      fi

      $output ${output_opts[@]} --messagex --done
      $output ${output_opts[@]} --messagecli --done
   else
      if [ ! "$SIGNAL_TYPE" = "NONE" ]; then
         local MSG="$SCRIPTNAME aborted! (SIGNAL_TYPE: $SIGNAL_TYPE)"
         echo "$MSG"
      fi
   fi

   if [ "$EXIT_CODE" = "" ]; then
      EXIT_CODE="1"
   fi

   exit "$EXIT_CODE"
}

## }}

trap_sigterm() {
   trap "error_handler" ERR

   SIGNAL_TYPE="SIGTERM"
   EXIT_CODE="143"
   ex_funct
}

trap "trap_sigterm" SIGTERM

trap_sigint() {
   trap "error_handler" ERR

   SIGNAL_TYPE="SIGINT"
   EXIT_CODE="130"
   ex_funct
}

trap "trap_sigint" SIGINT ## ctrl + c

trap_sigusr2() {
   trap "error_handler" ERR

   SIGNAL_TYPE="SIGUSR2"
   EXIT_CODE="0"
   ex_funct
}

trap "trap_sigusr2" SIGUSR2 ## msgcollector, zenity cancel button

cleanup() {
   trap "error_handler" ERR

   true "$FUNCNAME..."

   touch "/var/run/whonixcheck/${IDENTIFIER}_done"

   sync

   SIGNAL_TYPE="NONE"

   cd ..

   ## default exit code
   if [ "$EXIT_CODE" = "" ]; then
      EXIT_CODE="0"
   fi

   ex_funct
}
