#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

disclaimer() {
   if [ "$silent" -ge "1" ]; then
      true "silent is $silent. Skipping $FUNCNAME."
      return 0
   fi

   ## Not adding disclaimer here, because the kdialog info message would contain it,
   ## which would be too much.
   if [ "$AUTOSTARTED" = "1" ]; then
      return 0
   fi

   local MSG="<p>Whonix is produced independently of, with no guarantee from, The Tor Project. Whonix is experimental software. \
Do not rely on it for strong anonymity. <a href=$WHONIX_HOMEPAGE>$WHONIX_HOMEPAGE</a></p>"

   $output_x ${output_opts[@]} --messagex --typex "info" --message "$MSG"
   $output_cli ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
}
