#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

donate() {
   ## Do not ask for donations if a bug occurred. More important things have to be sorted out.
   if [ "$BUG" = "1" ]; then
      return
   fi

   local TYPE
   TYPE="$($output ${output_opts[@]} --identifier "$IDENTIFIER" --status --typexstatus)"
   ## Do not ask for donations if the user has something important to do.
   if [ "$TYPE" = "info" ]; then
      local MSG="<p>Please consider making a small reoccurring donation.
      See: <a href=https://www.whonix.org/wiki/Donate>https://www.whonix.org/wiki/Donate</a></p>"
      $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
   fi
}
