#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

function_manual_run() {
   if [ "$FUNCTION" = "" ]; then
      true
   else
      $FUNCTION
      cleanup
      return 0
   fi
}
