#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

root_check() {
   trap "error_handler" ERR

   if [ ! "$ROOT_CHECK" = "0" ]; then
      if [ "$(id -u)" != "0" ]; then
         local MSG="<p>Root Check Result: Ok, not running as root.</p>"
         if [ "$verbose" = "1" ]; then
            $output ${output_opts[@]} --messagex --typex "info" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG"
         fi
      else
         local MSG="<p>Please do not run whonixcheck as root.</p>"
         $output ${output_opts[@]} --messagex --typex "error" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG"
         EXIT_CODE="1"
         cleanup "1"
         return 0
      fi
   fi
}
