#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Required to run apt-get update as user (non-root).
## Required for whonixcheck function check_operating_system.
## Exception to run /usr/lib/apt-get-update as user
## is defined in /etc/sudoers.d/.

sigterm_trap() {
   if [ "$lastpid" = "" ]; then
      exit 143
   fi
   ps -p "$lastpid"
   if [ ! "$?" = "0" ]; then
      ## Already terminated.
      exit 143
   fi
   kill -sigterm "$lastpid"
   exit 143
}

trap "sigterm_trap" SIGTERM

apt-get update &
lastpid="$!"
echo "$lastpid" | sudo -u user tee "/var/run/whonixcheck/whonixcheck_apt_get_pid" > /dev/null
wait "$lastpid"

exit "$?"
