#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e
set -o pipefail
set -o errtrace

cleanup() {
   if [ -d "$temp_dir" ]; then
      rm --recursive --force "$temp_dir"
   fi
}

temp_dir="$(mktemp --directory)"

logfile="$temp_dir/apt-get_pid"
tee_fifo="$temp_dir/tee_fifo"

cleanup

trap "cleanup" EXIT

mkfifo "$tee_fifo"

tee "$logfile" < "$tee_fifo" &
tee_pid=$!

apt-get \
   ${1+"$@"} \
   1> "$tee_fifo" \
   2> "$tee_fifo" \
   &

apt_get_pid=$!

wait "$tee_pid"
wait "$apt_get_pid"
apt_get_exit_code="$?"

if [ ! "$apt_get_exit_code" = "0" ]; then
   exit "$apt_get_exit_code"
fi

log="$(cat "$logfile")"

while read -r -d $'\n' line; do
   first_two="${line:0:2}"
   first_two_lower_case="${first_two,,}"
   if [ "$first_two_lower_case" = "w:" ]; then
      exit 125
   fi
   if [ "$first_two_lower_case" = "e:" ]; then
      exit 125
   fi
done < <( echo "$log" )

exit "$apt_get_exit_code"
