#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

true "$BASH_SOURCE pid: $$"

if [ -f /etc/default/whonixcheckd ]; then
   source /etc/default/whonixcheckd
fi

for i in /etc/default/whonixcheckd.d/*; do
   if [ -f "$i" ]; then
      ## If the last character is a ~, ignore that file, because it was created
      ## by some editor, which creates backup files.
      if [ "${i: -1}" = "~" ]; then
         continue
      fi
      ## Skipping files such as .dpkg-old and .dpkg-dist.
      if ( echo "$i" | grep -q ".dpkg-" ); then
         true "skip $i"
         continue
      fi
      source "$i"
   fi
done

ex_funct() {
   echo "$SCRIPTNAME: $SIGNAL_TYPE received. Cleaning up..."

   if [ ! "$pid" = "" ]; then
      kill -sigterm "$pid"
   fi

   echo "$SCRIPTNAME: $SIGNAL_TYPE received. Exiting."
}

signal_sigint() {
   SIGNAL_TYPE="sigint"
   ex_funct
   exit 130
}

trap "trap_sigint" SIGINT ## ctrl + c

signal_sigterm() {
   SIGNAL_TYPE="sigterm"
   ex_funct
   exit 143
}

trap "signal_sigterm" SIGTERM

if [ "$debugging" = "true" ]; then
   set -x
   log_file="/home/user/whonixcheck.log"
   exec >  >(tee --append "$log_file")
   exec 2> >(tee --append "$log_file" >&2)
   bash -x /usr/bin/whonixcheck --autostart >>"$log_file" 2>&1 &
   pid="$!"
   wait "$pid" || true
else
   /usr/bin/whonixcheck --autostart >/dev/null 2>&1 &
   pid="$!"
   wait "$pid" || true
fi

sleep 3600 &
wait "$!"

while true; do

   if [ "$debugging" = "true" ]; then
      bash -x /usr/bin/whonixcheck --daemon >>"$log_file" 2>&1 &
      pid="$!"
      wait "$pid" || true
   else
      /usr/bin/whonixcheck --daemon >/dev/null 2>/dev/null &
      pid="$!"
      wait "$pid" || true
   fi

   sleep 3600 &
   pid="$!"
   wait "$pid" || true

done
