#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

true "$BASH_SOURCE pid: $$"

if [ -f /etc/default/whonixcheckd ]; then
   source /etc/default/whonixcheckd
fi

shopt -s nullglob
for i in /etc/default/whonixcheckd.d/*.conf /rw/config/default/whonixcheckd.d/*.conf; do
   bash_n_exit_code="0"
   bash_n_output="$(bash -n "$i" 2>&1)" || { bash_n_exit_code="$?" ; true; };
   if [ ! "$bash_n_exit_code" = "0" ]; then
      echo "Invalid config file: $i
bash_n_exit_code: $bash_n_exit_code
bash_n_output:
$bash_n_output" >&2
      exit 1
   fi
   source "$i"
done

ex_funct() {
   echo "$SCRIPTNAME: $SIGNAL_TYPE received. Cleaning up..."

   if [ ! "$pid" = "" ]; then
      kill -sigterm "$pid"
   fi

   echo "$SCRIPTNAME: $SIGNAL_TYPE received. Exiting."
}

signal_sigint() {
   SIGNAL_TYPE="sigint"
   ex_funct
   exit 130
}

trap "trap_sigint" SIGINT ## ctrl + c

signal_sigterm() {
   SIGNAL_TYPE="sigterm"
   ex_funct
   exit 143
}

trap "signal_sigterm" SIGTERM

if [ "$debugging" = "true" ]; then
   set -x
   log_file="/home/user/whonixcheck.log"
   exec >  >(tee --append "$log_file")
   exec 2> >(tee --append "$log_file" >&2)
   /usr/bin/whonixcheck --debug --autostart >>"$log_file" 2>&1 &
   pid="$!"
   wait "$pid" || true
else
   /usr/bin/whonixcheck --autostart >/dev/null 2>&1 &
   pid="$!"
   wait "$pid" || true
fi

sleep 3600 &
wait "$!"

while true; do

   if [ "$debugging" = "true" ]; then
      /usr/bin/whonixcheck --debug --daemon >>"$log_file" 2>&1 &
      pid="$!"
      wait "$pid" || true
   else
      /usr/bin/whonixcheck --daemon >/dev/null 2>/dev/null &
      pid="$!"
      wait "$pid" || true
   fi

   sleep 3600 &
   pid="$!"
   wait "$pid" || true

done
