#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

true "$BASH_SOURCE pid: $$"

if [ -f /etc/default/systemcheckd ]; then
   source /etc/default/systemcheckd
fi

shopt -s nullglob
for i in /etc/default/systemcheckd.d/*.conf /rw/config/default/systemcheckd.d/*.conf /usr/local/etc/default/systemcheckd.d/*.conf; do
   bash_n_exit_code="0"
   bash_n_output="$(bash -n "$i" 2>&1)" || { bash_n_exit_code="$?" ; true; };
   if [ ! "$bash_n_exit_code" = "0" ]; then
      echo "Invalid config file: $i
bash_n_exit_code: $bash_n_exit_code
bash_n_output:
$bash_n_output" >&2
      exit 1
   fi
   source "$i"
done

if [ "$debugging" = "true" ]; then
   set -x
   /usr/bin/systemcheck --cli --debug
else
   /usr/bin/systemcheck --cli &>/dev/null
fi

sleep 3600

while true; do

   if [ "$debugging" = "true" ]; then
      /usr/bin/systemcheck --cli --debug
   else
      /usr/bin/systemcheck --cli &>/dev/null
   fi

   sleep 3600
done
