#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

## provides: sanitize_variable
source /usr/lib/helper-scripts/sanitize_variable
source /usr/lib/systemcheck/uwt_tool.bsh

census_preparation() {
   if [ ! "$(whoami)" = "systemcheck" ]; then
      echo "ERROR: Exiting. Must be run under user systemcheck."
      exit 1
   fi

   virtualizer="$(systemd-detect-virt)" || true
   if [ "$virtualizer" = "oracle" ]; then
      known_virtualizer=yes
   elif [ "$virtualizer" = "kvm" ]; then
      known_virtualizer=yes
   elif [ "$virtualizer" = "qemu" ]; then
      known_virtualizer=yes
   fi
   if command -v qubesdb-read &>/dev/null ; then
      virtualizer=qubes
      known_virtualizer=yes
   fi

   ## Dedicated onion different from homepage.
   if test -f /usr/share/whonix/marker ; then
      true "INFO: Whonix detected."
      census_api_link="http://api.vel76jfvbl6rlq7qrgewrxpkzhulutx5tl4me4lwpzfje4sv6qgrckad.onion"
   else
      true "INFO: Kicksecure detected."
      census_api_link="http://api.ost5p5ju2eojz4ukhb7iib7pxvwrkm7yzeezamnzmxwidhnrtgad7yad.onion"
   fi

   if [ "$known_virtualizer" = "yes" ] ; then
      census_api_link="${census_api_link}/census_${virtualizer}"
   else
      census_api_link="${census_api_link}/census_unknown"
   fi

   ## TODO
   ## Testing.
   census_api_link="${census_api_link}/apitest"

   ## sets: GATEWAY_IP
   eval $(/usr/lib/helper-scripts/settings_echo)

   if test -e /usr/share/anon-gw-base-files/gateway || test -f /usr/share/anon-ws-base-files/workstation ; then
      [ -n "$SOCKS_PORT_CENSUS" ] || SOCKS_PORT_CENSUS="9114"
   else
      [ -n "$SOCKS_PORT_CENSUS" ] || SOCKS_PORT_CENSUS="9050"
   fi

   [ -n "$CURL_PROXY_CENSUS" ] || CURL_PROXY_CENSUS="--proxy socks5h://user:password@$GATEWAY_IP:$SOCKS_PORT_CENSUS"
}

check_census_lastrun() {
   ## One hour has 3600 seconds.
   ## A day has 86400 seconds.
   local MAX="86400"

   if [ -f "/var/lib/systemcheck/census/last_done" ]; then
      LASTRUN="$(cat "/var/lib/systemcheck/census/last_done")" || true
   fi

   if [ "$LASTRUN" = "" ]; then
      LASTRUN="$MAX"
   fi

   if [[ "$LASTRUN" != *[!0-9]* ]]; then
      true "$FUNCNAME: LASTRUN is strictly numeric."
   else
      echo "ERROR: $FUNCNAME: LASTRUN not strictly numeric. LASTRUN: $LASTRUN"
      ## Not strictly numeric.
      ## the census_completed function does almost the same
      LASTRUN="$MAX"
   fi

   ## read by sanitize_variable
   max_string_length="12"
   ## sets:
   ## actual_string_length
   ## sanitize_variable_output
   sanitize_variable "$LASTRUN"
   LASTRUN="$sanitize_variable_output"

   local CURRENTTIME
   CURRENTTIME="$(date --utc +%s)"

   DIFFERENCE="$(( $CURRENTTIME - $LASTRUN ))"

   if [ "$DIFFERENCE" -le "$MAX" ]; then
      echo "INFO: No need."
      exit 0
   fi

   echo "INFO: Attempting to count-in..."
}

census_completed() {
   local LASTRUN
   LASTRUN="$(date --utc +%s)"
   echo "$LASTRUN" | tee "/var/lib/systemcheck/census/last_done" > /dev/null
}

census_count_or_not() {
   if test -f /run/qubes/this-is-templatevm ; then
      echo "INFO: Skip in Qubes TemplateVM"
      exit 0
   fi

   if command -v qubesdb-read &>/dev/null ; then
      qubes_vm_persistence="$(qubesdb-read /qubes-vm-persistence)"
   fi

   if [ "$qubes_vm_persistence" = "none" ]; then
      echo "INFO: Skip in Qubes DispVM."
      exit 0
   fi

   ## TODO
#    if ! test -f /usr/share/anon-gw-base-files/gateway ; then
#       echo "INFO: Skip. Count only gateway."
#       exit 0
#    fi
}

census_do() {
   mkdir --parents "/var/lib/systemcheck/census"

   rm -f "/var/lib/systemcheck/census/census_result.txt"

   curl_exit_code="0"

   $CURL \
      --silent \
      --fail \
      $CURL_PROXY_CENSUS \
      --location \
      --retry-connrefused \
      --retry 3 \
      --retry-delay 3 \
      --retry-max-time 120 \
      --max-time 180 \
      --output "/var/lib/systemcheck/census/census_result.txt" \
      --request PUT \
      --data "gateway-sign-in" \
      "$census_api_link" \
      &

   lastpid="$!"
   wait "$lastpid" || { curl_exit_code="$?" ; true; };

   if [ ! "$curl_exit_code" = "0" ]; then
      local curl_status_message
      curl_status_message="$(/usr/lib/curl-scripts/curl_exit_codes "$curl_exit_code")"
      echo="ERROR: Failure.
curl exit code: $curl_status_message"
      exit 0
   fi

   echo "INFO: Success."

   census_completed
}

census_preparation
census_count_or_not
check_census_lastrun
census_do
