#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

systemd-notify --ready

while true; do
   systemd-notify --status="loop before"
   systemd-notify WATCHDOG=1

   /usr/lib/systemcheck/census

   systemd-notify --status="loop after"
   systemd-notify WATCHDOG=1

   ## 1 hour
   sleep 3600
done
