#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

/usr/lib/systemcheck/census

sleep 3600

while true; do
   /usr/lib/systemcheck/census

   sleep 3600
done
