#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

systemd-notify --pid="$$" --ready

while true; do
   echo "$0: INFO: start."
   systemd-notify --pid="$$" --status="loop before"
   systemd-notify --pid="$$" WATCHDOG=1

   /usr/lib/systemcheck/census

   systemd-notify --pid="$$" --status="loop after"
   systemd-notify --pid="$$" WATCHDOG=1
   echo "$0: INFO: end."

   ## 1 hour
   sleep 3600
done
